config/routes.rb
Rails.application.routes.draw do
  resources :agents

  root 'agents#index'

end

app/models/agent.rb
class Agent < ActiveRecord::Base
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: [:show, :edit, :update, :destroy]

  # GET /agents
  # GET /agents.json
  def index
    @agents = Agent.all
    render xml: @agents
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
    render xml: @agent
  end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents
  # POST /agents.json
  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1
  # PATCH/PUT /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: 'Agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = Agent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_params
      params.require(:agent).permit(:reference_number, :unit, :floor, :bedrooms, :bathrooms, :area, :description, :sale_price, :rent_price, :condo, :google_drive_folder, :dropbox_folder, :images_urls)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agents/_form.html.erb
<%= form_for(@agent) do |f| %>
  <% if @agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agent.errors.count, "error") %> prohibited this agent from being saved:</h2>

      <ul>
      <% @agent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reference_number %><br>
    <%= f.text_area :reference_number %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :floor %><br>
    <%= f.text_field :floor %>
  </div>
  <div class="field">
    <%= f.label :bedrooms %><br>
    <%= f.text_field :bedrooms %>
  </div>
  <div class="field">
    <%= f.label :bathrooms %><br>
    <%= f.text_field :bathrooms %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :sale_price %><br>
    <%= f.text_field :sale_price %>
  </div>
  <div class="field">
    <%= f.label :rent_price %><br>
    <%= f.text_field :rent_price %>
  </div>
  <div class="field">
    <%= f.label :condo %><br>
    <%= f.text_area :condo %>
  </div>
  <div class="field">
    <%= f.label :google_drive_folder %><br>
    <%= f.text_area :google_drive_folder %>
  </div>
  <div class="field">
    <%= f.label :dropbox_folder %><br>
    <%= f.text_area :dropbox_folder %>
  </div>
  <div class="field">
    <%= f.label :images_urls %><br>
    <%= f.text_area :images_urls %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agents/edit.html.erb
<h1>Editing Agent</h1>

<%= render 'form' %>

<%= link_to 'Show', @agent %> |
<%= link_to 'Back', agents_path %>

app/views/agents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Agents</h1>

<table>
  <thead>
    <tr>
      <th>Reference number</th>
      <th>Unit</th>
      <th>Floor</th>
      <th>Bedrooms</th>
      <th>Bathrooms</th>
      <th>Area</th>
      <th>Description</th>
      <th>Sale price</th>
      <th>Rent price</th>
      <th>Condo</th>
      <th>Google drive folder</th>
      <th>Dropbox folder</th>
      <th>Images urls</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= agent.reference_number %></td>
        <td><%= agent.unit %></td>
        <td><%= agent.floor %></td>
        <td><%= agent.bedrooms %></td>
        <td><%= agent.bathrooms %></td>
        <td><%= agent.area %></td>
        <td><%= agent.description %></td>
        <td><%= agent.sale_price %></td>
        <td><%= agent.rent_price %></td>
        <td><%= agent.condo %></td>
        <td><%= agent.google_drive_folder %></td>
        <td><%= agent.dropbox_folder %></td>
        <td><%= agent.images_urls %></td>
        <td><%= link_to 'Show', agent %></td>
        <td><%= link_to 'Edit', edit_agent_path(agent) %></td>
        <td><%= link_to 'Destroy', agent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agent', new_agent_path %>

app/views/agents/new.html.erb
<h1>New Agent</h1>

<%= render 'form' %>

<%= link_to 'Back', agents_path %>

app/views/agents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reference number:</strong>
  <%= @agent.reference_number %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @agent.unit %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @agent.floor %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @agent.bedrooms %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @agent.bathrooms %>
</p>

<p>
  <strong>Area:</strong>
  <%= @agent.area %>
</p>

<p>
  <strong>Description:</strong>
  <%= @agent.description %>
</p>

<p>
  <strong>Sale price:</strong>
  <%= @agent.sale_price %>
</p>

<p>
  <strong>Rent price:</strong>
  <%= @agent.rent_price %>
</p>

<p>
  <strong>Condo:</strong>
  <%= @agent.condo %>
</p>

<p>
  <strong>Google drive folder:</strong>
  <%= @agent.google_drive_folder %>
</p>

<p>
  <strong>Dropbox folder:</strong>
  <%= @agent.dropbox_folder %>
</p>

<p>
  <strong>Images urls:</strong>
  <%= @agent.images_urls %>
</p>

<%= link_to 'Edit', edit_agent_path(@agent) %> |
<%= link_to 'Back', agents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Property</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>